// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASqEy-sB3JzG8Nbv_xdHHEiaRgmFMp-1k',
    appId: '1:400306804266:web:f942977fc4fa47b31a1553',
    messagingSenderId: '400306804266',
    projectId: 'loginmovil-5260e',
    authDomain: 'loginmovil-5260e.firebaseapp.com',
    storageBucket: 'loginmovil-5260e.appspot.com',
    measurementId: 'G-0YQ6J3HQ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeAe2scczlwQPvIdHthsWZs7BBFv7ai7U',
    appId: '1:400306804266:android:89fab74626bd58f71a1553',
    messagingSenderId: '400306804266',
    projectId: 'loginmovil-5260e',
    storageBucket: 'loginmovil-5260e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBXF7y1koW1ek1tFAKQieKcVQQYvSAoI',
    appId: '1:400306804266:ios:889cfa25d89755de1a1553',
    messagingSenderId: '400306804266',
    projectId: 'loginmovil-5260e',
    storageBucket: 'loginmovil-5260e.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBXF7y1koW1ek1tFAKQieKcVQQYvSAoI',
    appId: '1:400306804266:ios:6f04f7261dc3cdf41a1553',
    messagingSenderId: '400306804266',
    projectId: 'loginmovil-5260e',
    storageBucket: 'loginmovil-5260e.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp.RunnerTests',
  );
}
